### ISSUE TITLE
Intermittent error 500 problems on transaction and event lists

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#1]
**Background** 
We're experiencing occasional problems with transaction lists:
- GET /users/:UserId/transactions/ 
- GET /wallets/:WalletId/transactions/
- GET /events/

You may occasionally receive an error 500 response which is partly caused by too many items in the list. To minimise the problem, you can try adding [filters](https://docs.mangopay.com/api-references/sort-lists/) to your request (particularly date filters).

**Environments**
Both sandbox and production are affected, however it is more likely in production

**Status**
We are analysing the problem and have identified a couple of solutions which we are currently working to implement.

**Comment by domingosl** [comment]
Any updates on this old issue?

**Comment by hobailey** [comment]
Hi @domingosl, thanks for your follow up, but I'm afraid to say that the problem still exists. I assure you we have been working hard on the solution since last year, but it's something major which takes a considerable amount of time to put in place (lots of heavy and very sensitive changes). 
This remains one of our top priorities, and we are moving things as fast as possible to resolve the issue :-)

**Comment by everhardt** [comment]
I am facing this issue as well and just found this discussion. Mangopay, you cannot be serious. You are aware of this issue for 8 months and still have not fixed this gaping hole in your API? If that happens to be your top priority, I wonder what happens with the rest. The whole idea of pagination is that this does not happen. Please let me know when this is fixed.

**Comment by hobailey** [comment]
Hi @everhardt, thanks for your comments, and I fully understand your frustration. Unfortunately even though there is pagination, this does not resolve the issue - because one of the problems we have comes from giving the total number of items/pages in the response header (hence meaning that even though you ask for a small subset of data via the pagination parameters, we still have to run queries on all of the data to get the info for these header parameters).
Although it remains one of our top priorities, it is very long and sensitive modifications that are required and across nearly all of our codebase, meaning we have to work progressively. And with only a small team, and the many new functionalities that we are adding each month, it's a question of balancing everything.

But I assure you, after spending much time analysing the problem, coming up with solutions, testing the impact/viability of these solutions by running small POCs etc, we are making progress. For example, we have completed the required work on the user lists, so these are no longer affected. Next month we'll be released another batch of work for wallets and their lists, and then finally the remaining elements (notably the transactions). We're hoping that the whole issue will therefore be resolved within the next 4/5 months.

**Comment by kubami** [comment]
I am also affected by the issue.
clientId - `iamin`.

I have never had that problem in the sandbox environment. Also I have never seen that issue for the user list (although the production UI loads for good 10 - 20s). 

The Events list NEVER loads and always ends in a timeout and 'Internal Server Error'. 
The same thing happens in the 'Recent Events' on the main dashboard - but there it just says there are no events...

It cannot be that there are too many items in my events table in the db since I have only started using production environment and have literally 4 'events' (confirmed by exporting a 'report'). I guess I am affected by the fact that the whole system has 'too many events'.

Is there any news on this?

**Comment by hobailey** [comment]
Hey @kubami, thanks for the feedback - it's always useful to have different perspectives. 

For the user list, we have already done the updates required, hence why you won't have any problems. If the UI is taking 10-20s, this is not normal however, and is a seperate problem we'd need to review (I'm assuming you're referring to the Dashboard?).

As for the events on the homepage, we put into production an update yesterday which removed this widget from the Dashboard homepage, so this should improve performance when using this page etc. As for the dedicated "events" page not working, it's not actually a question of how much data _your client_ has, it's more a question of all our client's data causing an issue. Limiting the date range to a couple of weeks for example should help though.

In terms of a more general update, a few weeks ago, another part of the project went live to improve wallet performance, and then in about a month, the next part of the project to improve transaction list performance will go live too. Shortly after, we'll do the events. And then the remaining objects will be done too.

I fully appreciate that this project has taken longer than initially planned, and I understand the inconvience and frustration that this must cause, but I promise that we are working on it as quickly and safely as possible :-)

**Comment by hobailey** [comment]
Quick update on this - we have since identified a second root cause of the problem affecting the events list. We're currently working on the fix for that and we'll deploy it by the end of January.

**Comment by Flowerskater** [comment]
Hi @hobailey,
Is there any news on this and the fix ?

**Comment by hobailey** [comment]
Hey @Flowerskater, I assure you that this issue remains of huge importance to us, and as previously explained, resolving it requires some major work to our application, as well large amounts of data migration (many millions of records in each case). One of the latest updates we did towards the project resulted in some unexpected results (which were immediately resolved) and therefore as a precaution we have temporarily haulted the project to work on further testing techniques and systems to ensure that future work towards this project is as rigorously tested as possible, before we release it to our live production environment. This secondary work has been going on for the last couple of months and is advancing well. We therefore hope to be able to get back to the original project in April, and from then onwards, performance improvements will continue to be noticed going forward. We're confident that this whole issue will be wrapped up by the summer, and we will have not only seriously reinforced our application and data management, but we'll also have much improved testing and montoring tools - all of which are of critical importance as Mangopay scales up at a challenging but exciting rate :-)

**Comment by hobailey** [comment]
Quick update: following some significant (and long!) work to our testing processes, we've been able to progress with the next stage of this project, and you'll notice that as of today's release, transaction lists are much much quicker to respond and you'll have no more error 500s for these endpoints 👍 
The next and final stages will follow in the coming months for the remaining objects, including the events lists.
Thank you again for your patience and feedback - we're nearly there now!

**Comment by mickaelpois** [comment]
Quick and happy update: we will improve events endpoints behaviour from our next release Ocelot, which should be live this week. Let's share what will happen:
* some technical fixes have been done and will be done, improving the way we search in our (bigger and bigger) events database.
* we add some new constraints on events endpoints, ensuring these endpoints are well used: events older than 45 days cannot be reached anymore. We know it could be felt as a restrictive new constraint, but be sure we have done our best effort to choose an acceptable value that is not painful for you in terms of usage data that we analyzed.

We will keep you posted here about every news about this production update to come.

**Comment by mickaelpois** [comment]
Quick and last update about this topic.
We have put into production everything listed above as you may have seen in the last weeks.
We are working harder this year on scalability and performances topics, and we truly hope it will be helpful for all of you.

Mickaël
