### ISSUE TITLE
null vs. {"Currency": "XXX","Amount": 0}

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#11]
Hi,
When creating a bank wire pay in (`POST` on `/payins/bankwire/direct`), I get a result containing:
`"DebitedFunds": null, "CreditedFunds": null, "Fees": null`

If right after I fetch the same pay in (`GET` on `/payins/{payin_id} `), I get a result containing:
`"DebitedFunds": {"Currency": "XXX","Amount": 0},"CreditedFunds": {"Currency": "XXX","Amount": 0},"Fees": {"Currency": "XXX","Amount": 0}`

Does `null` and `{"Currency": "XXX","Amount": 0}` have a different meaning or are they both expressing "no value"?
Shouldn't the pay in creation and retrieval methods return the same thing? (either `null` or `{"Currency": "XXX","Amount": 0}`)

Regards,

Laurent.

**Comment by hobailey** [comment]
Hi @ldesgrange, they have exactly the same meaning, you're right :-)
The POST and GET responses should indeed return the same thing in this case, but unfortunately they do not - since this would represent a breaking change, it is already something we've noted to correct in a subsequent API version.
