### ISSUE TITLE
Batch transfers

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay#12]
*This is a feature request.*

It would be great if the [`/transfers` API endpoint](https://docs.mangopay.com/api-references/transfers/) accepted a list of transfers.

Once a week we run our "payday", and as more users join our platform the number of transfers increases, which leads to our payday script taking longer to run. If we could send many transfers per request it would be a lot faster.

**Comment by hobailey** [comment]
Hi, this is a really great idea, and something we do indeed have planned but it's technically very complicated so it won't be available in the short term I'm afraid. But it's noted and we'll let you know once it's available :-)
