### ISSUE TITLE
PSP technical error on Sandbox

### ISSUE THREAD

**Issue by javiercr** [Mangopay/mangopay#20]
Hi,

Our tests are failing because the PSP is throwing an error on Sandbox mode when creating a preauthorization, this is the response body:

```json
{
  "Id": "13954901",
  "Tag": "",
  "CreationDate": 1465730689,
  "AuthorId": "13954898",
  "DebitedFunds": {
    "Currency": "EUR",
    "Amount": 101
  },
  "AuthorizationDate": 1465730690,
  "Status": "FAILED",
  "PaymentStatus": "CANCELED",
  "ExpirationDate": 1466335490,
  "PayInId": null,
  "ResultCode": "009199",
  "ResultMessage": "PSP technical error",
  "SecureMode": "DEFAULT",
  "CardId": "13954900",
  "SecureModeReturnURL": null,
  "SecureModeRedirectURL": null,
  "SecureModeNeeded": false,
  "PaymentType": "CARD",
  "ExecutionType": "DIRECT",
  "StatementDescriptor": null
}
```

However http://status.mangopay.com/ reports that the Sandbox API is fully operational. Is the status page automatically checking the actual status of the API or is it a manual switch that you guys enable when something goes wrong? Thanks!

**Comment by maximbatarchuk** [comment]
I have the same issue when try to create PayIn object

**Comment by javiercr** [comment]
@maximbatarchuk thanks for the feedback, I guess that means it's in fact an API issue.

@hobailey would be possible to have an status page that actually reflects the status of the full API, including the PSP?

**Comment by FlorianGuerrier** [comment]
Hi all, 

We've just created the status page : http://status.mangopay.com/incidents/j8jsvt05kk66. We pushed the incident on PSP side hoping to fix this asap. You're right @javiercr regarding your improvement proposal for the API status. Copy that!

**Comment by RaamR** [comment]
Hi All,

From morning I'm getting this  "PayInId"=>nil, "ResultCode"=>"009199", "ResultMessage"=>"PSP technicalerror", "SecureMode"=>"DEFAULT",  error. Is there any API issue in sandbox account.
