### ISSUE TITLE
Documentation is missing some field constraints

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#22]
Hi,

In the previous version of the documentation, there were constraints defined for lots of fields but those constraints are not displayed anymore in the new version of the documentation.

For instance `string` fields only shows `string` but the maximum allowed size is not displayed anymore. Or the PostalCode field in Address object only says it's a `string` and does not show that only alphanumeric characters and spaces are allowed.

It would be nice to have all those information back in the documentation.

**Comment by hobailey** [comment]
Hi @ldesgrange, thanks for bringing this up. I've just added some more constraint info, but let me know if you feel there is still some missing or if you have any queries.
