### ISSUE TITLE
Typo in "RessourceId" param for hooks

### ISSUE THREAD

**Issue by javiercr** [Mangopay/mangopay#23]
The current implementation of Hooks make requests to servers with the following params:
- `RessourceId`
- `EventId`
- `Date`

This is defined [in the docs](https://docs.mangopay.com/endpoints/v2/hooks#e246_the-hook-object):
> Notification format: http://www.your-site.com?EventType=`EventId`&RessourceId=`ResourceId`&Date=`Timestamp``

However `RessourceID` is misspelled and it's not consistent with the [Event object](https://docs.mangopay.com/endpoints/v2/events#e251_the-event-object) which has `ResourceId` (single `s`) as attribute.

I understand changing this now it may be problematic (our own app is already expecting the param with the typo). I think a mention about the typo in the documentation would be helpful for future users.

PS: this reminds me a lot to the famous typo in the HTTP header [referer](https://en.wikipedia.org/wiki/HTTP_referer).

**Comment by hobailey** [comment]
Thanks for flagging this up @javiercr - I've just added a note in the docs to highlight this more clearly :-) 
As you say, not something that is easily correctable without a new API version sadly.

**Comment by javiercr** [comment]
Kudos for adding that note so quick! 💪
