### ISSUE TITLE
Received hook notification with empty RessourceId (production)

### ISSUE THREAD

**Issue by javiercr** [Mangopay/mangopay#24]
We just received a `PAYOUT_NORMAL_FAILED` hook notification where `RessourceId` was empty:

>23.100.11.108 - - [15/Jul/2016:11:36:23 +0000] "GET /[url_redacted_for_security]?RessourceId=&EventType=PAYOUT_NORMAL_FAILED&Date=1468540800 HTTP/1.1" 200 11 "-" "-"

The IP is from Microsoft Azure, so I'm assuming is a real IP from Mangopay. Why would the API send a PAYOUT_NORMAL_FAILED without any `RessourceId`?

Thanks!

**Comment by hobailey** [comment]
@javiercr are you sure you (or someone in your team) weren't using the hook testing tool in the Dashboard?

**Comment by javiercr** [comment]
@hobailey yep, I'm pretty confident.

**Comment by hobailey** [comment]
Hey, I've just done some checks, and I confirm that this ping was indeed done from the production Dashboard hook simulator (who's IP is indeed 23.100.11.108) :-)

**Comment by javiercr** [comment]
@hobailey thanks for checking this. I don't really recall clicking the "test the hook" button, but I can't prove it, so I have to believe it was me accidentally.  Sorry to bother you guys.

**Comment by hobailey** [comment]
Well to be fair, we test the hook even during the update of the page too (ie without clicking the "test the hook" button) :-)
