### ISSUE TITLE
Does sandbox only work with EUR currency?

### ISSUE THREAD

**Issue by jonathanazulay** [Mangopay/mangopay#25]
I tried making a payin using SEK and just got `009199 - PSP technical error`, tried different amounts all under 100 EUR. When using EUR for the payin instead it worked.

**Comment by hobailey** [comment]
Hi @jonathanazulay, are you still having this problem? Could you send the infos (your ClientId and the IDs of the payins) to support@mangopay.com so they can take a look into this further for you please?
The sandbox works in all currencies, but you may need specific configuration for your account.

**Comment by jonathanazulay** [comment]
@hobailey Good, that's a relief. Yes, emailed now!
