### ISSUE TITLE
Documentation is misleading for deactivation of a bank account

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#26]
Hi,

Just a couple of things regarding the documentation here: https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e306_disactivate-a-bank-account

I believe that "disactivate" is not a proper word, "deactivate" is better.

The documentation says that the "Active" parameter is a `boolean` that is optional and could be `true` or `false`. One could think that it's possible to reactivate a bank account. But in fact only `false` is accepted.

Regards,

Laurent.

**Comment by jonathanazulay** [comment]
+1, not on this specific issue but in general I think the documentation has to be significantly improved. There are many inconsistencies and misleading information in there that should be fixed.

**Comment by hobailey** [comment]
Thanks for this @ldesgrange - I've just made some updates to make it clearer.
@jonathanazulay could you provide some specific examples please?

**Comment by jonathanazulay** [comment]
@hobailey I'm writing a list as I'm implementing, I'll send it over to you guys in near future :) A quick example, many attributes have incorrect types. Look for example at Card, ExpirationDate and Alias have Money as type.

**Comment by hobailey** [comment]
@jonathanazulay there was infact a bug with a few parameter types which we've just corrected, so things should be looking better now :-) Sorry for the confusion that may have caused.
As for any further feedback etc, please don't hesitate to send us your list when you're ready :-)
