### ISSUE TITLE
Any CC number with correct checksum works as sandbox test card

### ISSUE THREAD

**Issue by jonathanazulay** [Mangopay/mangopay#27]
I tried my own credit card and was surprised that it worked to do a payin with it. Then I tried some other test credit cards I found online and they all worked (payment goes through).

**Comment by hobailey** [comment]
Hi @jonathanazulay, this is indeed true - but for card payments, the PSP does not send the payment request to the banks. However, for several reasons, we would always advise that you use the specific testing methods: https://docs.mangopay.com/guide/testing-payments

By the way, this Github repo is only used for known issues with the API - if you have technical queries, please could you contact the support team directly (support@mangopay.com) :-)
