### ISSUE TITLE
Cannot register a Card Direct PayIn Object

### ISSUE THREAD

**Issue by asimadnan** [Mangopay/mangopay#29]
I am trying to register a Direct Card PayIn Object but facing an issue.

I sent this request to create a card payin Object.

```
{UserId: "15499020",
Currency: 'EUR',
Tag: 'Test Card Registration'}
```

this Responds with this data

```
cardreg = {"Id"=>"15548699"
 "Tag"=>"Test Card Registration"
 "CreationDate"=>1472647338
 "UserId"=>"15499020"
 "AccessKey"=>"1X0m87dmM2LiwFgxPLBJ"
 "PreregistrationData"=>"c9KuNKYJ7Ur8QlG3XTkcYBxKjMCPuqx6crvjIRj7TgEntpa_bg4fFU0Ri7xw2DciS4wCy-yiraxeE65tmxOe8A"
 "RegistrationData"=>nil
 "CardId"=>nil
 "CardType"=>"CB_VISA_MASTERCARD"
 "CardRegistrationURL"=>"https://homologation-webpayment.payline.com/webpayment/getToken"
 "ResultCode"=>nil
 "ResultMessage"=>nil
 "Currency"=>"EUR"
 "Status"=>"CREATED"}
```

Now I post this data to to `CardRegistrationURL` I received in previous response.

```
data = {
          data: cardreg['PreregistrationData'],
          accessKeyRef: cardreg['AccessKey'],
          cardNumber: 4970100000000154,
          cardExpirationDate: 1218,
          cardCvx: 123}
```

But the `CardRegistrationURL` is not responding, it gives a request time out error.
I have also tried posting these values via "http://mosaic-lab.com/demo/payline/request.php"
but same result, request time out.

What I might be doing wrong?

**Comment by hobailey** [comment]
Hi @asimadnan, I think this was perhaps just a short instability of our PSP - this function seems to be working fine now, but please let me know if it's not the case for you.
Out of interest, we did you see the reference to http://mosaic-lab.com/demo/payline/request.php?

**Comment by asimadnan** [comment]
@hobailey Did you mean *where did you see the reference to http://mosaic-lab.com/demo/payline/request.php?
Your support team gave me this link.

Also The issue still persists on my side
here is gif showing what is happening:
http://giphy.com/gifs/mangopay-l2SqdPKY6Lxg2owKY

**Comment by hobailey** [comment]
I did, sorry for the typo :-)
I think it is most likely to be an extension or antivirus blocking the call or something. If you try just visiting "https://homologation-webpayment.payline.com/webpayment/getToken" without a POST or using that form etc, do you still have the problem?

**Comment by asimadnan** [comment]
@hobailey 
yes if i visit it directly , or if i send a Post request from my rails application, the response is same, it says This site can’t be reached homologation-webpayment.payline.com took too long to respond.

I have even tried checking this url on http://www.isitdownrightnow.com/ to see if the issue is only on my side, but this URL is not responding to any request.

**Comment by hobailey** [comment]
http://www.isitdownrightnow.com/ only pings the root of the site, which in this case gives a 404, so it's not actually a fair test. https://homologation-webpayment.payline.com/webpayment/getToken responds correctly for me right now :-/
Could you try from a different network perhaps?
