### ISSUE TITLE
Custom payment templates are not working in Sandbox

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#30]
**Background**
* All [custom payment templates](https://docs.mangopay.com/guide/customising-the-design) are systematically not being taken into account
* You will see a default payment page of our PSP
* The payment itself and the payment process is otherwise not affected in anyway - it is a purely a visual issue

**Environments**
* The problem is only present in the sandbox environment

**Status**
* The problem has been identified and we are in touch with our PSP (a fix is required on their side to correct the issue)

**Comment by hobailey** [comment]
The problem is now resolved :-)

**Comment by jpvoisin** [comment]
Hello I can't get the template I've set instead of the default payment page, and I can see that it takes in count my template page url, as the layout has changed. Is it still an issue?
