### ISSUE TITLE
Confusion regarding KYC and payouts

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay#32]
The documentation reads "If a user does not have the sufficient KYC level for this payout, it will automatically pass to "FAILED" - more info"

Does this mean that the API response will state that the payout failed directly or will it still
start as CREATED and then switch to failed after the API response has been sent?
My tests on the sandbox shows that the response will say CREATED but I interpreted the documentation as if it would return an error right away.

**Comment by hobailey** [comment]
Hey @leihog, the API will always return a payout of `Status` = CREATED upon creation, and then once it's processed on our side (normally within a few seconds but this depends on the amount or extra checks we may need to run for fraud reasons etc), it will either turn to SUCCEEDED or FAILED. I've just updated the docs to make this clearer and avoid confusion in the future :-)
