### ISSUE TITLE
Timestamp is not appropriate for User/Birthday

### ISSUE THREAD

**Issue by sylvaindelezir** [Mangopay/mangopay#33]
Hi,

The minimum unix timestamp possible is Jan 01 1970 UTC. 
So what about people born before 1970 ? 
Is MangoPay only a service for younger people ? ;) 56+ years old people have some money to spend I presume.

Did I miss something or is there a deep conception issue here ?

**Comment by hobailey** [comment]
Hey there, try putting a negative sign for dates before the begining of Unix :-)

**Comment by sylvaindelezir** [comment]
Ok, i feel like an idiot. All these year... this is a revelation ! Thanks !
