### ISSUE TITLE
Crowdfunding wallet different currency 

### ISSUE THREAD

**Issue by ddxtreme** [Mangopay/mangopay#37]
Sorry if this is not the appropriate place to question about this.

I have a scenario where clientes can create campaigns, if the cliente is based for example in US the wallet of the campaign will be in USD.

What happen is that we cannot transfer funds from a EU user wallet (EUR) to the campaign, this means we cannot provide worldwide campaigns, but only users with wallets in the same currency.

Am i missing something, or thinking in the wrong way? Thanks

**Comment by hobailey** [comment]
Hey @ddxtreme, I suggest you discuss this with our support team (support@mangopay.com / https://www.mangopay.com/contact/) who'll be able to walk you through the options :-)
