### ISSUE TITLE
3DS test cards are currently unavailable

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#39]
**Background**
- The 3DS test cards are currently not working - payments will be accepted without the 3DS step in EUR but in other currencies the transactions requiring 3DS will fail

**Environments**
- Only the sandbox is affected by this problem

**Status**
- The problem has been identified and our PSP's supplier is working to resolve the situation as soon as possible

**Comment by hobailey** [comment]
The problem has now been resolved :-)

**Comment by picatextra** [comment]
Hi, can you check again ? the 3DS doesn't trigger
