### ISSUE TITLE
Country codes BQ, CW, ME, MF and SS are not supported

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#4]
Hi,

With API v2.01, when creating a natural user with an address in country Curaçao (ISO 3166-1 code: CW) I get the following error: `The requested value is not an ISO 3166-1 alpha-2 code which is expected` (I tested that on sandbox only)

Same issue with BQ (Bonaire), ME (Montenegro), MF (Saint Martin) and SS (South Sudan). I guess there are probably others.

**Comment by hobailey** [comment]
Hi @ldesgrange, thanks for flagging this up - this is already fixed in production in fact and will be the case in the sandbox either this afternoon or tomorrow morning :-)

**Comment by hobailey** [comment]
Just to let you know, the sandbox is now up to date and this problem no longer happens :-)
