### ISSUE TITLE
Some transaction hooks notifications and events not being triggered

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#45]
**Background**
- We've noticed that transaction hook notifications are not being sent/created for the following cases:
   - Transfer refunds
   - Payins created via a banking alias
   - Payout refunds

**Environments**
- Both the sandbox and production environments are affected

**Status**
- The problem has been identified and a fix completed - we'll be including it in our next release, due into production on 1st August hopefully

**Comment by olliebennett** [comment]
Hey Hugo, I assume this is now fixed + deployed?

**Comment by hobailey** [comment]
Hi @olliebennett, it is indeed, as of yesterday morning :-) Sorry for the late update on that.
