### ISSUE TITLE
Wallet with multiple owners

### ISSUE THREAD

**Issue by VivienCormier** [Mangopay/mangopay#48]
Hi,

I discovered recently that when an User do a `CardDirectPayin` to a wallet, the User is added to the list of the owners of the wallet.

So you can have a wallet with multiple owners but unfortunately the actual version of the api doesn’t work with multiple owners.

Now I have several wallets that are “broken” because they have multiple owners (Impossible to used it from the dashboard, etc.).

I think, it would be a good idea to indicate in your documentation that doing a `CardDirectPayin` has a side-effect that add the user to the list of the owner.

If your api doesn’t work when a wallet have more than one owner, it would be also nice to block the CardDirectPayin if the user isn’t the owner?

Do this side-effect also appear in another action than the `CardDirectPayin`?

Regards

**Comment by mickaelpois** [comment]
Hi @VivienCormier and thanks for your feedback.
I'm very surprised to hear that, could you give me more details, especially:
- if you're using a SDK, which one is it?
- if it was not happening to you before, from when does it happen?
If you want me to analyse what's wrond with more details (clientId, wallets Ids), you can easily contact our support.

Mickaël

**Comment by VivienCormier** [comment]
Hi @mickaelpois 

* I'm using the python-sdk.
* This behavior seems new (between 6th of December and the end of January)

Little story for more context:
We have contacted your technical support, because of a bug in the dashboard. We wasn't able to generate a report from a wallet. So the support told us that the report doesn't work because we have multiple owners to this wallet. According to the support we have multiple owners to this wallet because we're doing a Card Direct Payin (from many users) directly to this wallet instead of the wallet of the user.

Little exemple:
`User1` with `Wallet1` and `User2` with `Wallet2`.
If `User1` do `CardDirectPayin` to `Wallet2`. The `User1` become owner to the `Wallet2`.
According to your support to avoid this behavior we should always do:
`User1` do `CardDirectPayin` to `Wallet1` and do a `Transfert` from `Wallet1` to `Wallet2`.

Are you aware of this side-effect?

I'm little bit surprised that this side-effect isn't documented.

**Comment by mickaelpois** [comment]
I cannot reproduce this behaviour on our Sandbox env.
It's clearly not something we want, even if multiple owners was a feature we though about previously, our API is not supposed to support it yet.

Could you contact me directly by mail (mickael@mangopay.com) to share extra informations, especially some IDs of your "buggy" wallets?

Thanks.

Mickaël
