### ISSUE TITLE
Emails of Dispute creation contain links to a dev-dashboard

### ISSUE THREAD

**Issue by iammichiel** [Mangopay/mangopay#49]
Hi there,

Juste wanted to let you know that emails for Dispute Creation are linking to a dashboard-dev.mangopay.com. Probably your internal link to the new dashboard? Might want to notice the dev team of this regression ! 

Cheers.

**Comment by mickaelpois** [comment]
Hello @iammichiel,

Thanks for your prompt alert, very appreciated (as usual 👍 ) !
We will have a quick look at it and try to fix it ASAP.

Mickaël

**Comment by mickaelpois** [comment]
@iammichiel Finally, this issue will be fixed this week thanks to our next Butterfly release. 🙏 
Sorry for the long delay, and thanks again for pointing this.
