### ISSUE TITLE
Documentation error regarding BankWire PayIns

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay#5]
The documentation states that a call to  "/payins/bankwire/direct" should return 
    "BankAccount": {
        "Type": "IBAN",
        "OwnerName": "MangoPay Euro global",
        "OwnerAddress": "121 rue des leetchis",
        "IBAN": "CRLYFRPP",
        "BIC": "FR70 3000 2005 5000 0015 7845 Z02"
    }

The IBAN and BIC keys in the above example have been switched.

**Comment by hobailey** [comment]
Hi @leihog, thanks for this - I've just updated the page to correct this :-)
