### ISSUE TITLE
How Mango Pay HOOKS Works?

### ISSUE THREAD

**Issue by Aasif001** [Mangopay/mangopay#54]
May i know how this hooks works!
I have read the mango pay documentation from here https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object but I didn't get an idea about!
I just want to know how this hooks works and how we can implement it ? (are works like a cron job??)
Please let me know!
Thank You!

**Comment by dkirchhof** [comment]
Hey, i try to steer you in the right direction.  
1. You have to register a specifc route on your server.  
Example in nodejs + express:
```js
app.get('/payInSucceededHook', (req, res) => {
  // parse the query params here
});
```
2. Add this route to your mangopay account via the api or the [dashboard](https://dashboard.sandbox.mangopay.com/Developers).
3. As soon as a payin will succeed (in this example), your server will receive the request with some query params. The paying succeeded request will look like this: `GET ...serverUrl/payInSucceededHook?Date=1548806400&EventType=PAYIN_NORMAL_SUCCEEDED&RessourceId=123456`
  
If you want to try the hooks before implementing anything, you can use for example this website: https://webhook.site. There you can figure out, which params the hooks will append to your urls (there is no documentation about it). In the dashboard of your mangopay account there is a `test the hook` option. It will send a request to your specified url.

**Comment by mickaelpois** [comment]
Thanks @Aasif001 for your question and thanks @dkirchhof for your answer and help.
I hope it has been helpful, and feel free to discuss directly on our various SDKs repositories.

**Comment by julienreszka** [comment]
Can I verify that a request really comes from Mangopay?
