### ISSUE TITLE
Inconsistency between documentation and API result for BankWire PayIns

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay#6]
The documentation states that the response will contain OwnerName and OwnerAddress and give their example contents as:
   
  OwnerName: MangoPay Euro global 
  OwnerAddress: 121 rue des leetchis

In the actual result OwnerAddress was empty and OwnerName simply "MANGOPAY".
Am I to assume that the name and address in the documentation is correct and should be used instead of whatever is returned from the API?

Note: Only tested on the sandbox.

**Comment by hobailey** [comment]
@leihog these two fields are dynamic (ie could change at any moment, and may well be different between sandbox and production), and therefore your application should display whatever is given for each field. 
I've just added a Address value though, but as I say, they are dynamic and your site should be able to handle them as such please.

**Comment by leihog** [comment]
Thanks for responding and fixing this issue. Unfortunately your fix may have been a bit hasty. The API now correctly matches the documentation, however the PHP SDK is now incorrect as it expects the address field in the response to be a representation of an \MangoPay\Address.

**Comment by hobailey** [comment]
You're right - this is currently a known problem and something we're working to resolve asap. There's a seperate issue #7 if you wish to follow that.
