### ISSUE TITLE
OwnerAddress in PayIn BankWire is not detailed in v2.01

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#7]
**Background**
In v2.01 of the API, bank account and user address's were updated to a new "detailed" format ([more info](https://docs.mangopay.com/api-v2-01-overview/)) however the OwnerAddress field within the BankAccount returned for the POST /payins/bankwire/direct call is still a string, and not a detailed address object as for users and bank accounts.

**Environment**
All environments are impacted.

**Status**
We have identified the cause of the problem and will release a fix to the API shortly.

**Comment by TomVuillemin** [comment]
Any idea of when the fix will be released?

**Comment by hobailey** [comment]
@TomVuillemin - in the next few hours :-)
Sorry for the lack of updates!

**Comment by hobailey** [comment]
This is now fixed in production and sandbox :-)
