### ISSUE TITLE
Intermittent SSL errors in Chrome for card registrations and payin web

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay#8]
**Background** 
You may experiencing occasional problems when using the browser Chrome with the payin web flow via the RedirectURL and also when registering cards (POSTing the info to the CardRegistrationURL). You may receive an _ERR_SSL_VERSION_OR_CIPHER_MISMATCH_ browser error message. 
Note that other browsers are unaffeceted.

**Environments**
Only the sandbox is impacted

**Status**
We have identified the problem and our working with our PSP to find a solution. No fix date is available at this time unfortunately.

**Comment by javiercr** [comment]
Thanks god, I thought it was only me :). Looking forward for updates on this!

**Comment by hobailey** [comment]
We've not experienced this problem for a couple of months now, so I'm closing this - feel free to come back to me if you believe otherwise :-)
