### ISSUE TITLE
IBAN error message

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#9]
Hi,

On sandbox I'm getting different error messages for the same call (create an IBAN bank account with the IBAN missing):

``` log
2015-10-01 13:14:34: "IBAN":"The field IBAN must match the regular expression '^[a-zA-Z]{2}\\d{2}\\s*(\\w{4}\\s*){2,7}\\w{1,4}\\s*$'."
2015-11-02 10:19:02: "IBAN":"The IBAN field is required."
2015-11-27 10:31:25: "IBAN":"The field IBAN must match the regular expression '^[a-zA-Z]{2}\\d{2}\\s*(\\w{4}\\s*){2,7}\\w{1,4}\\s*$'."
2015-11-27 17:28:39: "IBAN":"The IBAN field is required."
```

I'm POSTing `{"Type":"IBAN","OwnerName":"Foo"}` to `https://api.sandbox.mangopay.com/v2.01/sdk-unit-tests/users/9661992/bankaccounts/IBAN` so I think the best error message is "The IBAN field is required.".

Could the error message be always the same for a given request?

**Comment by hobailey** [comment]
Hi @ldesgrange, effectively, if you provide no IBAN at all, you'll get the `The IBAN field is required.` message, whereas if you supply an invalid format, you'll get the `IBAN":"The field IBAN must match the regular expression '^[a-zA-Z]{2}\\d{2}\\s*(\\w{4}\\s*){2,7}\\w{1,4}\\s*$'.` message.

**Comment by ldesgrange** [comment]
That's my point, I always provide no IBAN at all and I get different error messages.

**Comment by hobailey** [comment]
You're absolutely right, I'm sorry for my quick response - upon further analysis, it does seem that the errors aren't systematic in some particular cases. I'll look into it further and get back to you :-)

**Comment by hobailey** [comment]
Hi @ldesgrange, just to update you on this, we've found out the problem and will pass a fix in the next couple of months hopefully - it's basically because there are two validation issues that are triggered, but the one that is infact shown in the response is random, hence how you're getting two different messages for the same request.

**Comment by hobailey** [comment]
We are no longer able to reproduce this problem, so we're assuming it's been fixed along the way :-)
